server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        - id: billing-service
          uri: http://localhost:8083
          predicates:
            - Path=/billing/**

        - id: analytics-service
          uri: http://localhost:8084
          predicates:
            - Path=/analytics/**
