name: CI/CD Swing Client

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build all modules (skip tests)
        run: mvn clean install -DskipTests

      - name: Run unit tests
        run: mvn test

      - name: Create Installer with jpackage
        run: |
          mkdir -p swing-client/installer
          jpackage \
            --type dmg \
            --name "EcommerceSwingClient" \
            --input swing-client/target \
            --main-jar swing-client-1.0.0.jar \
            --main-class org.example.swing.AppClient \
            --dest swing-client/installer \
            --icon swing-client/src/main/resources/icon.ico

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SwingClientInstaller-${{ matrix.os }}
          path: swing-client/installer
