name: CI/CD Pipeline - Multi-Module

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build all modules (skip tests for speed)
        run: mvn clean install -DskipTests

      - name: Run unit tests
        run: mvn test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=ecommerce-platform
            -Dsonar.projectName="Ecommerce Platform"
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Images (Microservices only)
        run: |
          docker build -t mamunrushdi/order-service ./order-service
          docker build -t mamunrushdi/billing-service ./billing-service
          docker build -t mamunrushdi/catalog-service ./catalog-service
          docker build -t mamunrushdi/analytics-service ./analytics-service
          docker build -t mamunrushdi/api-gateway ./api-gateway

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push mamunrushdi/order-service
          docker push mamunrushdi/billing-service
          docker push mamunrushdi/catalog-service
          docker push mamunrushdi/analytics-service
          docker push mamunrushdi/api-gateway
